# Generated by Django 2.1.4 on 2018-12-20 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_auto_20181218_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='资产名称')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='资产序列号')),
                ('status', models.SmallIntegerField(choices=[(0, '未分配'), (1, '已分配'), (2, '未知')], default=0, verbose_name='设备状态')),
                ('netmask', models.GenericIPAddressField(blank=True, null=True, verbose_name='掩码')),
                ('gateway_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('first_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='开始IP')),
                ('end_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='结尾IP')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='批准日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='所在机房')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Manufacturer', verbose_name='厂商')),
                ('tags', models.ManyToManyField(blank=True, to='assets.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': 'IP段表',
                'verbose_name_plural': 'IP段表',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin2', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by2', to=settings.AUTH_USER_MODEL, verbose_name='批准人'),
        ),
    ]
