# Generated by Django 2.1.4 on 2018-12-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20181220_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'ordering': ['-m_time'], 'verbose_name': 'IP表', 'verbose_name_plural': 'IP表'},
        ),
        migrations.RemoveField(
            model_name='ip',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='tags',
        ),
    ]
