# Generated by Django 2.1.4 on 2018-12-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_asset_hostname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'ordering': ['-ip'], 'verbose_name': 'IP表', 'verbose_name_plural': 'IP表'},
        ),
        migrations.AlterModelOptions(
            name='ip_asset',
            options={'ordering': ['-m_time'], 'verbose_name': 'IP段表', 'verbose_name_plural': 'IP段表'},
        ),
        migrations.RemoveField(
            model_name='ip',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='m_time',
        ),
    ]
