# Generated by Django 2.1.4 on 2018-12-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20181223_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='customer',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='客户名称'),
        ),
    ]
