# Generated by Django 2.1.4 on 2018-12-27 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0017_auto_20181226_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip_asset',
            options={'verbose_name': 'IP段表', 'verbose_name_plural': 'IP段表'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='memo',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='idc',
            old_name='memo',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='memo',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='network_asset',
            old_name='device_detail',
            new_name='dev_conf',
        ),
        migrations.RenameField(
            model_name='network_asset',
            old_name='device_log',
            new_name='dev_log',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='m_time',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='ip_asset',
            name='tags',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(default='11111111', max_length=128, unique=True, verbose_name='资产编码'),
        ),
        migrations.AddField(
            model_name='ip_asset',
            name='asset',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network_asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_network', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='network_asset',
            name='sn',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True, verbose_name='资产序列号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server_asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_server', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='server_asset',
            name='sn',
            field=models.CharField(default=datetime.datetime(2018, 12, 27, 17, 32, 16, 508572), max_length=128, unique=True, verbose_name='资产序列号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('network_device', '网络设备'), ('server_device', '服务器设备'), ('ip_device', 'IP资源'), ('o_device', '其他设备')], default='network_device', max_length=64, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '故障'), (3, '未知')], default=0, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='ip_asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已分配'), (1, '未分配'), (2, '未知')], default=0, verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='network_asset',
            name='firmware',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='固件版本'),
        ),
        migrations.AlterField(
            model_name='network_asset',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='network_asset',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, '交换机'), (1, '路由器'), (2, 'VPN设备'), (4, '防火墙')], default=0, verbose_name='设备类型'),
        ),
    ]
