# Generated by Django 2.1.4 on 2018-12-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_auto_20181227_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='comment',
            new_name='comments',
        ),
    ]
