# Generated by Django 2.1.4 on 2018-12-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_asset',
            name='status',
        ),
    ]
