# Generated by Django 2.1.4 on 2018-12-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Network_assets',
            new_name='Network_asset',
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('network_device', '网络设备'), ('server_device', '服务器'), ('o_device', '安全设备'), ('IDC', '机房')], default='server', max_length=64, null=True, verbose_name='资产类型'),
        ),
    ]
