# Generated by Django 2.1.5 on 2019-02-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190211_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='limit_in_speed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='入限速'),
        ),
        migrations.AlterField(
            model_name='port',
            name='limit_out_speed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='出限速'),
        ),
        migrations.AlterField(
            model_name='port',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_networkasset', to='assets.NetworkAsset', unique=True, verbose_name='所属设备'),
        ),
    ]
