# Generated by Django 2.1.4 on 2018-12-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_ip_ip_asset_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ip_asset_id',
            new_name='ip_asset',
        ),
    ]
