# Generated by Django 2.1.4 on 2018-12-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20181223_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='sn',
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ips_ip', to='assets.IP_Asset', verbose_name='所属IP段'),
        ),
    ]
