# Generated by Django 2.1.4 on 2018-12-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_ip_asset_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='businessunit',
            old_name='memo',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='eventlog',
            old_name='memo',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='ip',
            old_name='memo',
            new_name='comment',
        ),
    ]
