# Generated by Django 2.1.4 on 2019-01-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20190102_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='manage_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP'),
        ),
    ]
