# Generated by Django 2.1.5 on 2019-01-17 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20190103_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_asset', to=settings.AUTH_USER_MODEL, verbose_name='管理人'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='所属机房'),
        ),
    ]
