# Generated by Django 2.1.4 on 2018-12-20 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_auto_20181220_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='资产序列号')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('status', models.SmallIntegerField(choices=[(0, '未分配'), (1, '已分配'), (2, '未知')], default=0, verbose_name='IP状态')),
                ('customer', models.CharField(max_length=64, unique=True, verbose_name='客户名称')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='批准日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_ip', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员')),
                ('tags', models.ManyToManyField(blank=True, to='assets.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': 'IP表',
                'verbose_name_plural': 'IP表',
                'ordering': ['-c_time'],
            },
        ),
        migrations.RemoveField(
            model_name='network_asset',
            name='intranet_ip',
        ),
        migrations.RemoveField(
            model_name='network_asset',
            name='vlan_ip',
        ),
        migrations.AlterField(
            model_name='asset',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_asset', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_asset', to=settings.AUTH_USER_MODEL, verbose_name='批准人'),
        ),
        migrations.AlterField(
            model_name='ip_asset',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_ip_asset', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员'),
        ),
        migrations.AlterField(
            model_name='ip_asset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_ip_asset', to=settings.AUTH_USER_MODEL, verbose_name='批准人'),
        ),
        migrations.AlterField(
            model_name='ip_asset',
            name='end_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='结束IP'),
        ),
    ]
