# Generated by Django 2.1.4 on 2018-12-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20181221_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='hostname',
        ),
    ]
