# Generated by Django 2.1.4 on 2018-12-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20181223_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP'),
        ),
    ]
